import { describe, it, expect, beforeEach } from 'vitest'
import { computePlatformAudit } from './platform-audit'
import { PORTAL_RPC_ENFORCED } from '@/services/portal-data-service'
import { STRIPE_WEBHOOK_AUDIT } from '@/services/billing-service'
import { INVENTORY_AUDIT } from '@/services/inventory-service'
import { ONBOARDING_AUDIT } from '@/services/onboarding-service'
import { AUDIT_E2E_FULL_COVERAGE, AUDIT_I18N_COVERAGE, BILLING_PLAN_AUDIT, BULK_OPS_AUDIT, COMPANY_PROFILE_AUDIT, COMPANY_SWITCH_AUDIT, DISPATCH_AUDIT, ENTITY_UPDATE_AUDIT, ESTIMATE_CREATE_AUDIT, EXPENSE_AUDIT, FLEET_AUDIT, FUEL_LOG_AUDIT, INTEGRATION_PROBES_AUDIT, INVOICE_AUDIT, INVITE_AUDIT, PORTAL_AUDIT, PORTAL_REQUESTS_AUDIT, SAMPLE_IMPORT_AUDIT, TEAM_INVITE_AUDIT, VENDOR_PO_AUDIT } from '@/lib/audit-labels'
import { TYPED_SUPABASE_QUERIES } from '@/lib/supabase-queries'
import { MULTI_TENANT_SUPPORTED, MULTI_TENANT_MEMBERSHIP_RPC } from '@/services/company-service'

describe('platform-audit', () => {
  beforeEach(() => {
    localStorage.setItem('handymanos_locale', 'en')
  })

  it('returns combined audit score and recommendation ids', () => {
    const report = computePlatformAudit()
    expect(report.score).toBeGreaterThanOrEqual(0)
    expect(report.score).toBeLessThanOrEqual(10)
    expect(report.integrationScore).toBeGreaterThanOrEqual(0)
    expect(report.qualityScore).toBeGreaterThanOrEqual(0)
    expect(report.recommendationIds.length).toBeGreaterThan(0)
    expect(report.summaryKey).toMatch(/^(ready|needs_config)$/)
    expect(report.grade).toMatch(/^[A-C][+-]?$/)
  })

  it('includes observability recommendation when unset', () => {
    const report = computePlatformAudit()
    const hasObservabilityRec = report.recommendationIds.includes('observability')
    const allReady = report.recommendationIds.includes('all_ready')
    expect(hasObservabilityRec || allReady).toBe(true)
  })

  it('requires connect_supabase when live Supabase env is missing', () => {
    const report = computePlatformAudit()
    if (!import.meta.env.VITE_SUPABASE_URL || !import.meta.env.VITE_SUPABASE_ANON_KEY) {
      expect(report.recommendationIds).toContain('connect_supabase')
      expect(report.summaryKey).toBe('needs_config')
      expect(report.readyForProduction).toBe(false)
    }
  })

  it('uses compile-time quality gate constants', () => {
    expect(PORTAL_RPC_ENFORCED).toBe(true)
    expect(STRIPE_WEBHOOK_AUDIT).toBe(true)
    expect(AUDIT_I18N_COVERAGE).toBe(true)
    expect(INVENTORY_AUDIT).toBe(true)
    expect(ONBOARDING_AUDIT).toBe(true)
    expect(FLEET_AUDIT).toBe(true)
    expect(EXPENSE_AUDIT).toBe(true)
    expect(FUEL_LOG_AUDIT).toBe(true)
    expect(DISPATCH_AUDIT).toBe(true)
    expect(VENDOR_PO_AUDIT).toBe(true)
    expect(COMPANY_PROFILE_AUDIT).toBe(true)
    expect(PORTAL_AUDIT).toBe(true)
    expect(COMPANY_SWITCH_AUDIT).toBe(true)
    expect(INVITE_AUDIT).toBe(true)
    expect(BULK_OPS_AUDIT).toBe(true)
    expect(BILLING_PLAN_AUDIT).toBe(true)
    expect(TEAM_INVITE_AUDIT).toBe(true)
    expect(INVOICE_AUDIT).toBe(true)
    expect(SAMPLE_IMPORT_AUDIT).toBe(true)
    expect(PORTAL_REQUESTS_AUDIT).toBe(true)
    expect(ESTIMATE_CREATE_AUDIT).toBe(true)
    expect(ENTITY_UPDATE_AUDIT).toBe(true)
    expect(AUDIT_E2E_FULL_COVERAGE).toBe(true)
    expect(INTEGRATION_PROBES_AUDIT).toBe(true)
    expect(TYPED_SUPABASE_QUERIES).toBe(true)
    expect(MULTI_TENANT_SUPPORTED).toBe(true)
    expect(MULTI_TENANT_MEMBERSHIP_RPC).toBe('get_accessible_companies')

    const report = computePlatformAudit()
    const typed = report.checks.find((check) => check.id === 'typed_data')
    const portal = report.checks.find((check) => check.id === 'portal_rpc')
    const stripeAudit = report.checks.find((check) => check.id === 'stripe_webhook_audit')
    const auditI18n = report.checks.find((check) => check.id === 'audit_i18n')
    const inventoryAudit = report.checks.find((check) => check.id === 'inventory_audit')
    const onboardingAudit = report.checks.find((check) => check.id === 'onboarding_audit')
    const fleetAudit = report.checks.find((check) => check.id === 'fleet_audit')
    const expenseAudit = report.checks.find((check) => check.id === 'expense_audit')
    const fuelLogAudit = report.checks.find((check) => check.id === 'fuel_log_audit')
    const dispatchAudit = report.checks.find((check) => check.id === 'dispatch_audit')
    const vendorPoAudit = report.checks.find((check) => check.id === 'vendor_po_audit')
    const companyProfileAudit = report.checks.find((check) => check.id === 'company_profile_audit')
    const portalAudit = report.checks.find((check) => check.id === 'portal_audit')
    const companySwitchAudit = report.checks.find((check) => check.id === 'company_switch_audit')
    const inviteAudit = report.checks.find((check) => check.id === 'invite_audit')
    const bulkOpsAudit = report.checks.find((check) => check.id === 'bulk_ops_audit')
    const billingPlanAudit = report.checks.find((check) => check.id === 'billing_plan_audit')
    const teamInviteAudit = report.checks.find((check) => check.id === 'team_invite_audit')
    const invoiceAudit = report.checks.find((check) => check.id === 'invoice_audit')
    const sampleImportAudit = report.checks.find((check) => check.id === 'sample_import_audit')
    const portalRequestsAudit = report.checks.find((check) => check.id === 'portal_requests_audit')
    const estimateCreateAudit = report.checks.find((check) => check.id === 'estimate_create_audit')
    const entityUpdateAudit = report.checks.find((check) => check.id === 'entity_update_audit')
    const auditE2eFull = report.checks.find((check) => check.id === 'audit_e2e_full')
    const integrationProbesAudit = report.checks.find((check) => check.id === 'integration_probes')
    const multi = report.checks.find((check) => check.id === 'multi_tenant')
    const liveBackend = report.checks.find((check) => check.id === 'live_backend')

    expect(typed?.ok).toBe(Boolean(liveBackend?.ok))
    expect(portal?.ok).toBe(Boolean(liveBackend?.ok))
    expect(stripeAudit?.ok).toBe(Boolean(liveBackend?.ok))
    expect(auditI18n?.ok).toBe(Boolean(liveBackend?.ok))
    expect(inventoryAudit?.ok).toBe(Boolean(liveBackend?.ok))
    expect(onboardingAudit?.ok).toBe(Boolean(liveBackend?.ok))
    expect(fleetAudit?.ok).toBe(Boolean(liveBackend?.ok))
    expect(expenseAudit?.ok).toBe(Boolean(liveBackend?.ok))
    expect(fuelLogAudit?.ok).toBe(Boolean(liveBackend?.ok))
    expect(dispatchAudit?.ok).toBe(Boolean(liveBackend?.ok))
    expect(vendorPoAudit?.ok).toBe(Boolean(liveBackend?.ok))
    expect(companyProfileAudit?.ok).toBe(Boolean(liveBackend?.ok))
    expect(portalAudit?.ok).toBe(Boolean(liveBackend?.ok))
    expect(companySwitchAudit?.ok).toBe(Boolean(liveBackend?.ok))
    expect(inviteAudit?.ok).toBe(Boolean(liveBackend?.ok))
    expect(bulkOpsAudit?.ok).toBe(Boolean(liveBackend?.ok))
    expect(billingPlanAudit?.ok).toBe(Boolean(liveBackend?.ok))
    expect(teamInviteAudit?.ok).toBe(Boolean(liveBackend?.ok))
    expect(invoiceAudit?.ok).toBe(Boolean(liveBackend?.ok))
    expect(sampleImportAudit?.ok).toBe(Boolean(liveBackend?.ok))
    expect(portalRequestsAudit?.ok).toBe(Boolean(liveBackend?.ok))
    expect(estimateCreateAudit?.ok).toBe(Boolean(liveBackend?.ok))
    expect(entityUpdateAudit?.ok).toBe(Boolean(liveBackend?.ok))
    expect(auditE2eFull?.ok).toBe(Boolean(liveBackend?.ok))
    expect(integrationProbesAudit?.ok).toBe(Boolean(liveBackend?.ok))
    expect(multi?.ok).toBe(Boolean(liveBackend?.ok))
  })
})
